name: website
description: Gelesen website https://gelesen.app
version: 0.1.5
publish_to: none

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  highlight: ^0.7.0
  http: ^1.6.0
  jaspr: ^0.22.2
  jaspr_router: ^0.8.1
  markdown: ^7.3.0
  universal_web: ^1.1.1+1

dev_dependencies:
  build_runner: ^2.11.0
  jaspr_builder: ^0.22.2
  build_web_compilers: ^4.4.11

jaspr:
  mode: static