name: blog
description: A documentation site built with Jaspr
version: 0.0.1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  jaspr: ^0.22.1
  jaspr_content: ^0.4.4
  jaspr_router: ^0.8.0

dev_dependencies:
  build_runner: ^2.10.4
  build_web_compilers: ^4.4.6
  jaspr_builder: ^0.22.1
  jaspr_lints: ^0.6.0
  lints: ^6.0.0

jaspr:
  mode: static
