name: blog
description: A documentation site built with Jaspr
version: 0.0.1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  jaspr: ^0.22.2
  jaspr_content: ^0.4.5
  jaspr_router: ^0.8.1

dev_dependencies:
  build_runner: ^2.11.0
  build_web_compilers: ^4.4.10
  jaspr_builder: ^0.22.2
  jaspr_lints: ^0.6.0
  lints: ^6.1.0

jaspr:
  mode: static
